{
 "title": "VPA Recommendations",
 "tags": [ "Autoscaling" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "targetKind",
    "label": "Kind",
    "query": "label_values(kube_verticalpodautoscaler_spec_updatepolicy_updatemode, target_kind)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_verticalpodautoscaler_spec_updatepolicy_updatemode{target_kind=~\"$targetKind\"}, namespace)"
   },
   {
    "name": "targetName",
    "label": "Target",
    "query": "label_values(kube_verticalpodautoscaler_spec_updatepolicy_updatemode{target_kind=~\"$targetKind\", namespace=\"$namespace\"}, target_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Update Mode",
   "type": "stat",
   "description": "The update mode of the VPA.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_verticalpodautoscaler_spec_updatepolicy_updatemode{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\"} > 0",
     "legendFormat": "{{ update_mode }}"
    }
   ]
  },
  {
   "title": "Memory Recommendation vs Memory Usage",
   "type": "graph",
   "description": "Shows the memory recommendation (target). \nThe graph also shows the actual average usage of each container, the lower and upper bounds of the VPA, and the min and max allowed values. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$targetName(.+)\", container!=\"POD\"}) / count(count(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$targetName(.+)\", container!=\"POD\"}) by(pod))",
     "legendFormat": "Avg Usage"
    },
    {
     "expr": "sum(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"memory\"}) by (pod)",
     "legendFormat": "Recommendation"
    },
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"memory\"}",
     "legendFormat": "LowerBound"
    },
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"memory\"}",
     "legendFormat": "UpperBound"
    }
   ]
  },
  {
   "title": "VPA Memory Recommendations vs Requests and Limits",
   "type": "graph",
   "description": "Shows the memory recommendation (target), and the current request and limit of the container.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"memory\"})",
     "legendFormat": "Recommendation"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$targetName(.+)\", resource=\"memory\"}) / count(count(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$targetName(.+)\", resource=\"memory\"}) by(pod))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"$targetName(.+)\"}) / count(count(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"$targetName(.+)\"}) by(pod))",
     "legendFormat": "Limits"
    },
    {
     "expr": "kube_verticalpodautoscaler_spec_resourcepolicy_container_policies_minallowed{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"memory\"}",
     "legendFormat": "MinAllowed"
    },
    {
     "expr": "kube_verticalpodautoscaler_spec_resourcepolicy_container_policies_maxallowed{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"memory\"}",
     "legendFormat": "MaxAllowed"
    }
   ]
  },
  {
   "title": "CPU Recommendation vs CPU Usage",
   "type": "graph",
   "description": "Shows the cpu recommendation (target). \nThe graph also shows the actual average usage of each container, the lower and upper bounds of the VPA, and the min and max allowed values. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$targetName-(.+)\", container!=\"POD\"}[2m])) / count(count(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$targetName(.+)\", container!=\"POD\"}) by(pod))",
     "legendFormat": "Avg Usage"
    },
    {
     "expr": "sum(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "Recommendation"
    },
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"cpu\"}",
     "legendFormat": "LowerBound"
    },
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"cpu\"}",
     "legendFormat": "UpperBound"
    }
   ]
  },
  {
   "title": "VPA CPU Recommendations vs Requests and Limits",
   "type": "graph",
   "description": "Shows the cpu recommendation (target), and the current request and limit of the container.\n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"cpu\"}) ",
     "legendFormat": "Recommendation"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$targetName(.+)\", resource=\"cpu\"}) / count(count(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$targetName(.+)\", resource=\"cpu\"}) by(pod))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$targetName(.+)\", resource=\"cpu\"}) / count(count(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$targetName(.+)\", resource=\"cpu\"}) by(pod))",
     "legendFormat": "Limits"
    },
    {
     "expr": "kube_verticalpodautoscaler_spec_resourcepolicy_container_policies_minallowed{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"cpu\"}",
     "legendFormat": "MinAllowed"
    },
    {
     "expr": "kube_verticalpodautoscaler_spec_resourcepolicy_container_policies_maxallowed{namespace=\"$namespace\", target_kind=\"$targetKind\", target_name=\"$targetName\", resource=\"cpu\"}",
     "legendFormat": "MaxAllowed"
    }
   ]
  },
  {
   "title": "Too few replicas",
   "type": "table",
   "description": "vpa-updater too-few-replicas logs from elasticsearch",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "log",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.pod_name:\"vpa-updater\" AND (log:\"too few replicas\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "table",
   "description": "vpa-updater eviction logs from elasticsearch",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "log",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.pod_name:\"vpa-updater\" AND (log:\"evicting\" OR log:\"evicted\") AND (log:\"$targetName\" AND log:\"$namespace\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All Evictions",
   "type": "table",
   "description": "vpa-updater eviction logs from elasticsearch",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "log",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.pod_name:\"vpa-updater\" AND (log:\"evicting\" OR log:\"evicted\")",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}